name: My Job
platform:
  os: linux
  arch: arm64
env:
  ENV1: some-value
  ENV2: another-value
secrets:
  SECRET1: ref:my-secret
stages:
  - name: Check Python Version
    image: python:3.13.2
    script: |-
      python3 --version
      echo "$ENV1"
      sleep 30
  - name: Hello World
    image: python:3.13.2
    script: |-
      echo "Hello World"
  - name: Say Hello
    image: python:3.13.2
    run_after:
      - Check Python Version
    script: |-
      echo "Hello my beautiful wife :)"
  - name: Say Goodbye
    image: python:3.13.2
    run_after:
      - Say Hello
    script: |-
      echo "Goodbye"
