apiVersion: hello

triggers:
  pushes:
    branches:
      - "*"
    tags:
      - "*"
    paths:
      exclude:
        - "docs/**"
      include:
        - "**/*.java"

  prs:
    branches:
      - "*"
