# comment a

triggers:
  pushes:
    branches:
      - "*"
    tags:
      - "*"
    paths:
      exclude:
        - "docs/**"
      # include:
      #   - "**/*.java"

  prs:
    branches:
      - "*"

jobs:
  build:
    when: ${{git.ref == "develop"}}
    call: ./my-build-job.yml
    inputs:
      parameter1: ${{env.ABC}}
    stages:
      - run: echo "hello build"
      - run: sleep 30
      - run: echo "goodbye build"

  deploy:
    depends-on: [build]
    stages:
      - run: echo "hello deploy"
      - run: sleep 30
      - run: echo "goodbye deploy"
